Logging!

diff --git a/bin/terraform b/bin/terraform
--- a/bin/terraform
+++ b/bin/terraform
@@ -1,6 +1,40 @@
 #!/usr/bin/env bash
-set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
+set -uo pipefail;
 
-program="${0##*/}"
-exec "$(dirname "$(command -v "${0}")")/tfenv" exec "${@}"
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ -n "${TFENV_DEBUG:-""}" ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ -n "${TFENV_DEBUG:-""}" ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ -n "${TFENV_DEBUG:-""}" ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
+
+log 'debug' "program=\"${0##*/}\"";
+
+declare tfenv_path="$(dirname "$(command -v "${0}")")/tfenv";
+
+log 'debug' "Exec: \"${tfenv_path}\" exec \"${@}\"";
+exec "${tfenv_path}" exec "${@}" \
+  || log 'error' "Failed to exec: \"${tfenv_path}\" exec \"${@}\"";
+
+log 'error' 'This line should not be reachable. Something catastrophic has occurred';
diff --git a/bin/tfenv b/bin/tfenv
--- a/bin/tfenv
+++ b/bin/tfenv
@@ -1,63 +1,90 @@
 #!/usr/bin/env bash
-set -e
-if [ -n "${TFENV_DEBUG}" ]; then
-  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
-  set -x
-fi
+set -euo pipefail;
 
-# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
-readlink_f() {
-  local target_file="${1}"
-  local file_name
+declare arg="${1:-""}";
 
-  while [ "${target_file}" != "" ]; do
-    cd "$(dirname ${target_file})"
-    file_name="$(basename "${target_file}")"
-    target_file="$(readlink "${file_name}")"
-  done
+if [ -z "${TFENV_ROOT:-""}" ]; then
+  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
+  readlink_f() {
+    local target_file="${1}";
+    local file_name;
 
-  echo "$(pwd -P)/${file_name}"
-}
+    while [ "${target_file}" != "" ]; do
+      cd "$(dirname ${target_file})";
+      file_name="$(basename "${target_file}")";
+      target_file="$(readlink "${file_name}")";
+    done;
 
-if [ -z "${TFENV_ROOT}" ]; then
-  TFENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)"
+    echo "$(pwd -P)/${file_name}";
+  }
+
+  TFENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
 else
   TFENV_ROOT="${TFENV_ROOT%/}"
 fi
-export TFENV_ROOT
-PATH="${TFENV_ROOT}/libexec:${PATH}"
-export PATH
+export TFENV_ROOT;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ -n "${TFENV_DEBUG:-""}" ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
+
+log 'debug' "Prepending ${TFENV_ROOT}/libexec to PATH";
+PATH="${TFENV_ROOT}/libexec:${PATH}";
+export PATH;
+
+log 'debug' "Setting TFENV_DIR to ${PWD}";
 export TFENV_DIR="${PWD}"
 
 abort() {
-  { if [ "${#}" -eq 0 ]; then cat -
-    else echo "tfenv: ${*}"
-    fi
-  } >&2
-  exit 1
+  log 'debug' 'Aborting...';
+  {
+    if [ "${#}" -eq 0 ]; then
+      cat -;
+    else
+      echo "tfenv: ${*}";
+    fi;
+  } >&2;
+  exit 1;
 }
 
-command="${1}"
-case "${command}" in
-"" )
-  { tfenv---version
-    tfenv-help
-  } | abort
-  ;;
--v | --version )
-  exec tfenv---version
-  ;;
--h | --help )
-  exec tfenv-help
-  ;;
-* )
-  command_path="$(command -v "tfenv-${command}" || true)"
-  if [ -z "${command_path}" ];then
-    { echo "no such command '${command}'"
-      tfenv-help
-    } | abort
-  fi
-  shift 1
-  exec "${command_path}" "${@}"
-  ;;
-esac
+case "${arg}" in
+  "")
+    log 'debug' 'No argument provided, dumping version and help and aborting';
+    {
+      tfenv---version;
+      tfenv-help;
+    } | abort;
+    ;;
+  -v | --version )
+    log 'debug' 'tfenv version requested...';
+    exec tfenv---version;
+    ;;
+  -h | --help )
+    log 'debug' 'tfenv help requested...';
+    exec tfenv-help;
+    ;;
+  *)
+    log 'debug' "Long argument provided: ${arg}";
+    command_path="$(command -v "tfenv-${arg}" || true)";
+    log 'debug' "Resulting command-path: ${command_path}";
+    if [ -z "${command_path}" ]; then
+      {
+        echo "No such command '${arg}'";
+        tfenv-help;
+      } | abort;
+    fi;
+    shift 1;
+    log 'debug' "Exec: \"${command_path}\" \"${@}\"";
+    exec "${command_path}" "${@}";
+    ;;
+esac;
+
+log 'error' 'This line should not be reachable. Something catastrophic has occurred';
diff --git a/libexec/tfenv---version b/libexec/tfenv---version
--- a/libexec/tfenv---version
+++ b/libexec/tfenv---version
@@ -9,15 +9,48 @@
 # where `num_commits` is the number of commits since `version` was
 # tagged.
 
-set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
+set -uo pipefail;
 
-version=$(awk '/^##/{ print $2; exit}' "${TFENV_ROOT}"/CHANGELOG.md)
-git_revision=""
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
+
+log 'debug' 'Scraping tfenv version from CHANGELOG.md';
+version="$(awk '/^##/{ print $2; exit}' "${TFENV_ROOT}/CHANGELOG.md")" \
+  || log 'error' 'Failed to scrape version from CHANGELOG.md';
+git_revision="";
 
 if cd "${BASH_SOURCE%/*}" 2>/dev/null && git remote -v 2>/dev/null | grep -q tfenv; then
-  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
-  git_revision="${git_revision#v}"
-fi
+  log 'debug' 'Getting git revision...';
+  git_revision="$(git describe --tags HEAD 2>/dev/null || true)";
+  log 'debug' "Stripping git revision string ${git_revision}";
+  git_revision="${git_revision#v}";
+fi;
 
-echo "tfenv ${git_revision:-$version}"
+echo "tfenv ${git_revision:-$version}";
+
+exit 0;
diff --git a/libexec/tfenv-exec b/libexec/tfenv-exec
--- a/libexec/tfenv-exec
+++ b/libexec/tfenv-exec
@@ -13,10 +13,53 @@
 # is equivalent to:
 #   PATH="$TFENV_ROOT/versions/0.7.0/bin:$PATH" terraform plan
 
-set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
+set -uo pipefail;
 
-export TFENV_VERSION="$(tfenv-version-name)"
-TF_BIN_PATH="${TFENV_ROOT}/versions/${TFENV_VERSION}/terraform"
-export PATH="${TF_BIN_PATH}:${PATH}"
-exec "${TF_BIN_PATH}" "${@}"
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}";
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}";
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh";
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
+
+log 'debug' 'Getting version from tfenv-version-name';
+TFENV_VERSION="$(tfenv-version-name)" \
+  && log 'debug' "TFENV_VERSION is ${TFENV_VERSION}" \
+  || {
+    # Errors will be logged from tfenv-version name,
+    # we don't need to trouble STDERR with repeat information here
+    log 'debug' 'Failed to get version from tfenv-version-name';
+    exit 1;
+  };
+export TFENV_VERSION;
+
+TF_BIN_PATH="${TFENV_ROOT}/versions/${TFENV_VERSION}/terraform";
+export PATH="${TF_BIN_PATH}:${PATH}";
+log 'debug' "TF_BIN_PATH added to PATH: ${TF_BIN_PATH}";
+log 'debug' "Executing: ${TF_BIN_PATH} ${@}";
+
+exec "${TF_BIN_PATH}" "${@}" \
+  || log 'error' "Failed to execute: ${TF_BIN_PATH} ${@}";
+
+exit 0;
diff --git a/libexec/tfenv-help b/libexec/tfenv-help
--- a/libexec/tfenv-help
+++ b/libexec/tfenv-help
@@ -1,8 +1,36 @@
 #!/usr/bin/env bash
 
-[ -n "${TFENV_DEBUG}" ] && set -x
+set -uo pipefail;
 
-echo "Usage: tfenv <command> [<options>]
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
+
+echo 'Usage: tfenv <command> [<options>]
 
 Commands:
    install       Install a specific version of Terraform
@@ -10,4 +38,6 @@ Commands:
    uninstall     Uninstall a specific version of Terraform
    list          List all installed versions
    list-remote   List all installable versions
-"
+';
+
+exit 0;
diff --git a/libexec/tfenv-list b/libexec/tfenv-list
--- a/libexec/tfenv-list
+++ b/libexec/tfenv-list
@@ -1,25 +1,69 @@
 #!/usr/bin/env bash
 
-[ -n "${TFENV_DEBUG}" ] && set -x
-source "${TFENV_ROOT}/libexec/helpers"
+set -uo pipefail;
+
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
 
 [ "${#}" -ne 0 ] \
-  && error_and_die "usage: tfenv list"
+  && log 'error' "usage: tfenv list"
 
 [ -d "${TFENV_ROOT}/versions" ] \
-  || error_and_die "No versions available. Please install one with: tfenv install"
+  || log 'error' 'No versions available. Please install one with: tfenv install'
 
 [[ -x "${TFENV_ROOT}/versions" && -r "${TFENV_ROOT}/versions" ]] \
-  || error_and_die "tfenv versions directory is inaccessible!"
+  || log 'error' "tfenv versions directory is inaccessible: ${TFENV_ROOT}/versions";
+
+version_name="$(tfenv-version-name)" \
+  && log 'debug' "tfenv-version-name reported: ${version_name}" \
+  || log 'error' "tfenv-version-name failed";
+export version_name;
+
+export version_file="$(tfenv-version-file)" \
+  && log 'debug' "tfenv-version-file reported: ${version_file}" \
+  || log 'error' "tfenv-version-file failed";
+export version_file;
 
 print_version () {
-    if [ "${1}" == "$(tfenv-version-name)" ]; then
-        echo "* ${1} (set by $(tfenv-version-file))"
-    else
-        echo "  ${1}"
-    fi
-}
+  if [ "${1}" == "${version_name}" ]; then
+    echo "* ${1} (set by ${version_file})";
+  else
+    echo "  ${1}";
+  fi;
+};
 
-for local_version in $(ls -1 "${TFENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3); do
-    print_version "${local_version}"
-done
+log 'debug' 'Listing versions...';
+local_versions=($(ls -1 "${TFENV_ROOT}/versions" \
+  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3));
+
+log 'debug' "Local versions: ${local_versions[@]}";
+
+log 'debug' 'Printing versions...';
+for local_version in ${local_versions[@]}; do
+  print_version "${local_version}";
+done;
diff --git a/libexec/tfenv-list-remote b/libexec/tfenv-list-remote
--- a/libexec/tfenv-list-remote
+++ b/libexec/tfenv-list-remote
@@ -1,14 +1,44 @@
 #!/usr/bin/env bash
-set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
-source "${TFENV_ROOT}/libexec/helpers"
+
+set -uo pipefail;
+
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
 
 if [ "${#}" -ne 0 ];then
   echo "usage: tfenv list-remote" 1>&2
-  exit 1
+  exit 1;
 fi
 
 TFENV_REMOTE="${TFENV_REMOTE:-https://releases.hashicorp.com}"
+log 'debug' "TFENV_REMOTE: ${TFENV_REMOTE}";
+declare remote_versions="$(curlw -sf "${TFENV_REMOTE}/terraform/")";
+log 'debug' "Remote versions available: ${remote_versions}";
 curlw -sf "${TFENV_REMOTE}/terraform/" \
   | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha|oci)[0-9]*)?" \
-  | uniq
+  | uniq;
diff --git a/libexec/tfenv-min-required b/libexec/tfenv-min-required
--- a/libexec/tfenv-min-required
+++ b/libexec/tfenv-min-required
@@ -1,42 +1,67 @@
 #!/usr/bin/env bash
 # Usage: tfenv min-required
 # Summary: Detect the minimal required version from *tf files
-set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
+
+set -uo pipefail;
+
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
 
 bailout() {
-  >&2 echo "Error: Could not determine required_version based on your terraform sources.
+  log 'error' 'Error: Could not determine required_version based on your terraform sources.
 Make sure at least one of your *tf files includes a required version section like
 terraform {
-  required_version = \">= 0.0.0\"
+  required_version = ">= 0.0.0"
 }
 
-see https://www.terraform.io/docs/configuration/terraform.html for details
-
-"
-  exit 1
-}
+see https://www.terraform.io/docs/configuration/terraform.html for details';
+};
 
 find_min_required() {
-  local root="${1}"
+  local root="${1}";
 
-  versions="$(grep -h -R required_version --include '*tf' "$root"/* | tr -c -d '0-9. ~=!<>' )"
+  versions="$(grep -h -R required_version --include '*tf' "$root"/* | tr -c -d '0-9. ~=!<>' )";
 
   if [[ "${versions}" =~ ([~=!<>]{0,2}[[:blank:]]*[0-9]+[0-9.]+)[^0-9]* ]]; then
-    found_min_required="${BASH_REMATCH[1]}"
+    found_min_required="${BASH_REMATCH[1]}";
 
     if [[ "${found_min_required}" =~ ^!=.+ ]]; then
-      echo "Error: Min required version is a negation ($found_min_required) - we cannot guess the desired one."
-      bailout
+      log 'debug' "Error: Min required version is a negation ($found_min_required) - we cannot guess the desired one.";
+      bailout;
     else
-      found_min_required="$(echo "$found_min_required" | tr -c -d '0-9.')"
-      #echo "Min required version is detected as ${found_min_required}"
-      echo "${found_min_required}"
-      exit 0
-    fi
-  fi
+      found_min_required="$(echo "$found_min_required" | tr -c -d '0-9.')";
+      #echo "Min required version is detected as ${found_min_required}";
+      echo "${found_min_required}";
+      exit 0;
+    fi;
+  fi;
 
-  bailout
-}
+  bailout;
+};
 
-find_min_required "${TFENV_DIR}"
+find_min_required "${TFENV_DIR}";
diff --git a/libexec/tfenv-uninstall b/libexec/tfenv-uninstall
--- a/libexec/tfenv-uninstall
+++ b/libexec/tfenv-uninstall
@@ -1,39 +1,66 @@
 #!/usr/bin/env bash
 
-[ -n "${TFENV_DEBUG}" ] && set -x
-source "${TFENV_ROOT}/libexec/helpers"
+set -uo pipefail;
 
-[ "${#}" -gt 1 ] && error_and_die "usage: tfenv uninstall [<version>]"
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
 
-declare version_requested version regex
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
+
+[ "${#}" -gt 1 ] && log 'error' 'usage: tfenv uninstall [<version>]';
+
+declare version_requested version regex;
 
 if [ -z "${1}" ]; then
-  version_file="$(tfenv-version-file)"
-  if [ "${version_file}" != "${TFENV_ROOT}/version" ];then
-    version_requested="$(cat "${version_file}" || true)"
-  fi
+  version_file="$(tfenv-version-file)";
+  if [ "${version_file}" != "${TFENV_ROOT}/version" ]; then
+    version_requested="$(cat "${version_file}" || true)";
+  fi;
 else
-  version_requested="${1}"
-fi
+  version_requested="${1}";
+fi;
 
 if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
-  version="${version_requested%%\:*}"
-  regex="${version_requested##*\:}"
+  version="${version_requested%%\:*}";
+  regex="${version_requested##*\:}";
 elif [[ "${version_requested}" =~ ^latest$ ]]; then
-  version="${version_requested}"
-  regex=""
+  version="${version_requested}";
+  regex="";
 else
-  version="${version_requested}"
-  regex="^${version_requested}$"
-fi
+  version="${version_requested}";
+  regex="^${version_requested}$";
+fi;
 
-[ -n "${version}" ] || error_and_die "Version is not specified"
-version="$(tfenv-list | sed -E 's/^(\*| )? //g; s/ \(set by .+\)$//' | grep -e "${regex}" | head -n 1)"
-[ -n "${version}" ] || error_and_die "No versions matching '${1}' found in local"
+[ -n "${version}" ] || log 'error' "Version is not specified";
+version="$(tfenv-list | sed -E 's/^(\*| )? //g; s/ \(set by .+\)$//' | grep -e "${regex}" | head -n 1)";
+[ -n "${version}" ] || log 'error' "No versions matching '${1}' found in local";
 
-dst_path="${TFENV_ROOT}/versions/${version}"
+dst_path="${TFENV_ROOT}/versions/${version}";
 if [ -f "${dst_path}/terraform" ]; then 
-  info "Uninstall Terraform v${version}"
-  rm -r "${dst_path}"
-  info "\033[0;32mTerraform v${version} is successfully uninstalled\033[0;39m"
-fi
+  log 'info' "Uninstall Terraform v${version}";
+  rm -r "${dst_path}";
+  log 'info' "Terraform v${version} is successfully uninstalled";
+fi;
diff --git a/libexec/tfenv-use b/libexec/tfenv-use
--- a/libexec/tfenv-use
+++ b/libexec/tfenv-use
@@ -1,55 +1,91 @@
 #!/usr/bin/env bash
 
-[ -n "${TFENV_DEBUG}" ] && set -x
-source "${TFENV_ROOT}/libexec/helpers"
+set -uo pipefail;
 
-[ "${#}" -ne 1 ] && error_and_die "usage: tfenv use <version>"
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
 
-declare version_requested version regex
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
 
-version_requested="${1}"
+[ "${#}" -ne 1 ] && log 'error' 'usage: tfenv use <version>';
+
+declare version_requested version regex min_required version_file;
+
+version_requested="${1}";
 
 if [[ "${version_requested}" =~ ^min-required$ ]]; then
-  echo "Detecting minimal required version..."
-  found_min_required="$(tfenv-min-required)"
+  log 'info' 'Detecting minimum required version...';
+  min_required="$(tfenv-min-required)" \
+    || log 'error' 'tfenv-min-required failed';
 
-  if [[ $? -eq 0 ]]; then
-      echo "Min required version is detected as ${found_min_required}"
-      version_requested="${found_min_required}"
-  else
-    exit 1
-  fi
-fi
+  log 'info' "Minimum required version detected: ${min_required}";
+  version_requested="${min_required}";
+fi;
 
 if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
-  version="${version_requested%%\:*}"
-  regex="${version_requested##*\:}"
+  version="${version_requested%%\:*}";
+  regex="${version_requested##*\:}";
+  log 'debug' "Version uses latest keyword with regex: ${regex}";
 elif [[ "${version_requested}" =~ ^latest$ ]]; then
-  version="${version_requested}"
-  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
+  version="${version_requested}";
+  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$";
+  log 'debug' "Version uses latest keyword alone. Forcing regex to match stable versions only: ${regex}";
 else
-  version="${version_requested}"
-  regex="^${version_requested}$"
-fi
+  version="${version_requested}";
+  regex="^${version_requested}$";
+  log 'debug' "Version is explicit: ${version}. Regex enforces the version: ${regex}";
+fi;
 
 [ -d "${TFENV_ROOT}/versions" ] \
-  || error_and_die "No versions of terraform installed. Please install one with: tfenv install"
+  || log 'error' 'No versions of terraform installed. Please install one with: tfenv install';
 
+log 'debug' "Searching ${TFENV_ROOT}/versions for latest version matching ${regex}";
 version="$(\ls "${TFENV_ROOT}/versions" \
   | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
   | grep -e "${regex}" \
   | head -n 1
-)"
+)";
 
-[ -n "${version}" ] || error_and_die "No installed versions of terraform matched '${1}'"
+[ -n "${version}" ] \
+  && log 'debug' "Found version: ${version}" \
+  || log 'error' "No installed versions of terraform matched '${1}'";
 
-target_path="${TFENV_ROOT}/versions/${version}"
+target_path="${TFENV_ROOT}/versions/${version}";
 [ -f "${target_path}/terraform" ] \
-  || error_and_die "Version directory for ${version} is present, but the terraform binary is not! Manual intervention required."
+  || log 'error' "Version directory for ${version} is present, but the terraform binary is not! Manual intervention required.";
 [ -x "${target_path}/terraform" ] \
-  || error_and_die "Version directory for ${version} is present, but the terraform binary is not executable! Manual intervention required. "
+  || log 'error' "Version directory for ${version} is present, but the terraform binary is not executable! Manual intervention required.";
 
-info "Switching to v${version}"
-echo "${version}" > "$(tfenv-version-file)" || error_and_die "'switch to v${version} failed'"
-terraform --version 1>/dev/null || error_and_die "'terraform --version' failed. Something is seriously wrong"
-info "Switching completed"
+log 'info' "Switching to v${version}";
+
+version_file="$(tfenv-version-file)";
+log 'debug' "Writing \"${version}\" to \"${version_file}\"";
+echo "${version}" > "${version_file}" \
+  || log 'error' "Switch to v${version} failed";
+
+terraform --version 1>/dev/null \
+  || log 'error' "'terraform --version' failed. Something is seriously wrong";
+log 'info' "Switching completed";
diff --git a/libexec/tfenv-version-file b/libexec/tfenv-version-file
--- a/libexec/tfenv-version-file
+++ b/libexec/tfenv-version-file
@@ -1,20 +1,58 @@
 #!/usr/bin/env bash
 # Usage: tfenv version-file
 # Summary: Detect the file that sets the current tfenv version
-set -e
-[ -n "${TFENV_DEBUG}" ] && set -x
+
+set -uo pipefail;
+
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
 
 find_local_version_file() {
-  local root="${1}"
+  log 'debug' "Looking for a version file in ${1}";
+  local root="${1}";
   while ! [[ "${root}" =~ ^//[^/]*$ ]]; do
     if [ -e "${root}/.terraform-version" ]; then
-      echo "${root}/.terraform-version"
-      return 0
-    fi
-    [ -n "${root}" ] || break
-    root="${root%/*}"
-  done
-  return 1
+      log 'debug' "Found at ${root}/.terraform-version";
+      echo "${root}/.terraform-version";
+      return 0;
+    else
+      log 'debug' "Not found at ${root}/.terraform-version";
+    fi;
+    [ -n "${root}" ] || break;
+    root="${root%/*}";
+  done;
+  log 'debug' "No version file found in ${1}";
+  return 1;
 }
 
-find_local_version_file "${TFENV_DIR}" || find_local_version_file "${HOME}" || echo "${TFENV_ROOT}/version"
+if ! find_local_version_file "${TFENV_DIR:-${PWD}}"; then
+  if ! find_local_version_file "${HOME}"; then
+    log 'debug' "No version file found in search paths. Defaulting to TFENV_ROOT: ${TFENV_ROOT}/version";
+    echo "${TFENV_ROOT}/version";
+  fi;
+fi;
diff --git a/libexec/tfenv-version-name b/libexec/tfenv-version-name
--- a/libexec/tfenv-version-name
+++ b/libexec/tfenv-version-name
@@ -1,37 +1,75 @@
 #!/usr/bin/env bash
-# Summary: Show the current Terraform version
-set -e
+# Summary: Show the currently-selected terraform version
 
-[ -n "${TFENV_DEBUG}" ] && set -x
-source "${TFENV_ROOT}/libexec/helpers"
+set -uo pipefail;
+
+# Ensure we can execute standalone
+if [ -n "${TFENV_ROOT:-""}" ]; then
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
+  fi;
+else
+  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
+  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
+    [ -n "${TFENV_HELPERS:-""}" ] \
+      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
+      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
+  fi;
+fi;
+
+if [ -n "${TFENV_HELPERS:-""}" ]; then
+  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
+else
+  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  if source "${TFENV_ROOT}/lib/helpers.sh"; then
+    log 'debug' 'Helpers sourced successfully';
+  else
+    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+    exit 1;
+  fi;
+fi;
 
 [ -d "${TFENV_ROOT}/versions" ] \
-  || error_and_die "No versions of terraform installed. Please install one with: tfenv install"
+  || log 'error' 'No versions of terraform installed. Please install one with: tfenv install';
 
-TFENV_VERSION_FILE="$(tfenv-version-file)"
-TFENV_VERSION="$(cat "${TFENV_VERSION_FILE}" || true)"
+TFENV_VERSION_FILE="$(tfenv-version-file)" \
+  && log 'debug' "TFENV_VERSION_FILE retrieved from tfenv-version-file: ${TFENV_VERSION_FILE}" \
+  || log 'error' 'Failed to retrieve TFENV_VERSION_FILE from tfenv-version-file';
+
+TFENV_VERSION="$(cat "${TFENV_VERSION_FILE}" || true)" \
+  && log 'debug' "TFENV_VERSION specified in TFENV_VERSION_FILE: ${TFENV_VERSION}";
 
 if [[ "${TFENV_VERSION}" =~ ^latest.*$ ]]; then
-  [[ "${TFENV_VERSION}" =~ ^latest\:.*$ ]] && regex="${TFENV_VERSION##*\:}"
+  log 'debug' 'TFENV_VERSION uses "latest" keyword';
+
+  if [[ "${TFENV_VERSION}" =~ ^latest\:.*$ ]]; then
+    regex="${TFENV_VERSION##*\:}";
+    log 'debug' "\"latest\" keyword uses regex: ${regex}";
+  fi;
+
   version="$(\ls "${TFENV_ROOT}/versions" \
     | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
     | grep -e "${regex}" \
-    | head -n 1
-  )"
-  [ -n "${version}" ] || error_and_die "No installed versions of terraform matched '${TFENV_VERSION}'"
-  TFENV_VERSION="${version}"
-fi
+    | head -n 1)";
+
+  if [ -n "${version}" ]; then
+    log 'debug' "Version selected: ${version}";
+    TFENV_VERSION="${version}"
+  else
+    log 'error' "No installed versions of terraform matched '${TFENV_VERSION}'";
+  fi;
+
+else
+  log 'debug' 'TFENV_VERSION does not use "latest" keyword';
+fi;
 
 [ -z "${TFENV_VERSION}" ] \
-  && error_and_die "Version could not be resolved (set by ${TFENV_VERSION_FILE} or tfenv use <version>)"
+  && log 'error' "Version could not be resolved (set by ${TFENV_VERSION_FILE} or tfenv use <version>)";
 
-version_exists() {
-  local version="${1}"
-  [ -d "${TFENV_ROOT}/versions/${version}" ]
-}
-
-if version_exists "${TFENV_VERSION}"; then
-  echo "${TFENV_VERSION}"
+if [ -d "${TFENV_ROOT}/versions/${TFENV_VERSION}" ]; then
+  echo "${TFENV_VERSION}";
 else
-  error_and_die "version '${TFENV_VERSION}' is not installed (set by ${TFENV_VERSION_FILE})"
-fi
+  log 'error' "version '${TFENV_VERSION}' is not installed (set by ${TFENV_VERSION_FILE})";
+fi;
