Fix install and uninstall from .terraform-version in path with spaces

diff --git a/libexec/helpers b/libexec/helpers
--- a/libexec/helpers
+++ b/libexec/helpers
@@ -24,3 +24,27 @@ function curlw () {
 
   curl ${TLS_OPT} "$@"
 }
+
+function get_version_requested () {
+  if [ -z "${1}" ]; then
+    version_file="$(tfenv-version-file)"
+    if [ "${version_file}" != "${TFENV_ROOT}/version" ];then
+      version_requested="$(cat "${version_file}" || true)"
+    fi
+  else
+    version_requested="${1}"
+  fi
+
+  if [[ "${version_requested}" =~ ^min-required$ ]]; then
+    echo "Detecting minimal required version..."
+    found_min_required="$(tfenv-min-required)"
+
+    if [[ $? -eq 0 ]]; then
+      echo "Min required version is detected as ${found_min_required}"
+      version_requested=${found_min_required}
+    else
+      exit 1
+    fi
+  fi
+}
+
