automatically pick and use required_version from terraform section of tf files

diff --git a/libexec/tfenv-version-name b/libexec/tfenv-version-name
--- a/libexec/tfenv-version-name
+++ b/libexec/tfenv-version-name
@@ -56,6 +56,18 @@ for dir in libexec bin; do
   esac;
 done;
 
+# If on MacOS with Homebrew, use GNU grep
+# This allows keybase login detection to work on Mac,
+# and is required to be able to detect terraform version
+# from "required_version" setting in "*.tf" files
+if [[ $(uname) == 'Darwin' ]] && [ $(which brew) ]; then
+  if ! [ $(which ggrep) ]; then
+    brew install grep;
+  fi
+  shopt -s expand_aliases
+  alias grep=ggrep;
+fi
+
 #####################
 # Begin Script Body #
 #####################
@@ -65,10 +77,36 @@ if [[ -z "${TFENV_TERRAFORM_VERSION:-""}" ]]; then
     && log 'debug' "TFENV_VERSION_FILE retrieved from tfenv-version-file: ${TFENV_VERSION_FILE}" \
     || log 'error' 'Failed to retrieve TFENV_VERSION_FILE from tfenv-version-file';
 
-  TFENV_VERSION="$(cat "${TFENV_VERSION_FILE}" || true)" \
-    && log 'debug' "TFENV_VERSION specified in TFENV_VERSION_FILE: ${TFENV_VERSION}";
+  if [ "${TFENV_VERSION_FILE}" = "${TFENV_CONFIG_DIR}/version" ]; then
+    log 'debug' 'Tryng to set version from "required_version" under "terraform" section'
 
-  TFENV_VERSION_SOURCE="${TFENV_VERSION_FILE}";
+    versions="$( echo $(cat {*.tf,*.tf.json} 2>/dev/null | grep -h required_version) | grep  -o '\([0-9]\+\.\?\)\{2,3\}\(-[a-z]\+[0-9]\+\)\?')";
+    if [[ "${versions}" =~ ([~=!<>]{0,2}[[:blank:]]*[0-9]+[0-9.]+)[^0-9]*(-[a-z]+[0-9]+)? ]]; then
+      found_min_required="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
+      if [[ "${found_min_required}" =~ ^!=.+ ]]; then
+        log 'debug' "required_version is a negation - we cannot guess the desired one, skipping.";
+      else
+        found_min_required="$(echo "$found_min_required")";
+
+        # Probably not an advisable way to choose a terraform version,
+        # but this is the way this functionality works in terraform:
+        # add .0 to versions without a minor and/or patch version (e.g. 12.0)
+        while ! [[ "${found_min_required}" =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; do
+          found_min_required="${found_min_required}.0";
+        done;
+        TFENV_VERSION="${found_min_required}";
+      fi;
+    fi;
+
+    TFENV_VERSION_SOURCE='terraform{required_version}'
+  fi;
+
+  if [[ -z "${TFENV_VERSION:-""}" ]]; then
+    TFENV_VERSION="$(cat "${TFENV_VERSION_FILE}" || true)" \
+      && log 'debug' "TFENV_VERSION specified in TFENV_VERSION_FILE: ${TFENV_VERSION}";
+
+    TFENV_VERSION_SOURCE="${TFENV_VERSION_FILE}";
+  fi;
 else
   TFENV_VERSION="${TFENV_TERRAFORM_VERSION}" \
     && log 'debug' "TFENV_VERSION specified in TFENV_TERRAFORM_VERSION: ${TFENV_VERSION}";
