Rewrite script initialisation to cleanly handle symlinks and prep all scripts for standalone

diff --git a/libexec/tfenv-install b/libexec/tfenv-install
--- a/libexec/tfenv-install
+++ b/libexec/tfenv-install
@@ -2,33 +2,62 @@
 
 set -uo pipefail;
 
-# Ensure we can execute standalone
-if [ -n "${TFENV_ROOT:-""}" ]; then
-  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
-    [ -n "${TFENV_HELPERS:-""}" ] \
-      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
-      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
-  fi;
+####################################
+# Ensure we can execute standalone #
+####################################
+
+function early_death() {
+  echo "[FATAL] ${0}: ${1}" >&2;
+  exit 1;
+};
+
+if [ -z "${TFENV_ROOT:-""}" ]; then
+  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
+  readlink_f() {
+    local target_file="${1}";
+    local file_name;
+
+    while [ "${target_file}" != "" ]; do
+      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TFENV_ROOT";
+      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TFENV_ROOT";
+      target_file="$(readlink "${file_name}")";
+    done;
+
+    echo "$(pwd -P)/${file_name}";
+  };
+
+  TFENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
+  [ -n ${TFENV_ROOT} ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine TFENV_ROOT";
 else
-  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
-  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
-    [ -n "${TFENV_HELPERS:-""}" ] \
-      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
-      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
-  fi;
+  TFENV_ROOT="${TFENV_ROOT%/}";
 fi;
+export TFENV_ROOT;
 
 if [ -n "${TFENV_HELPERS:-""}" ]; then
   log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
 else
-  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
+  [ "${TFENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh";
   if source "${TFENV_ROOT}/lib/helpers.sh"; then
     log 'debug' 'Helpers sourced successfully';
   else
-    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
-    exit 1;
+    early_death "Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh";
   fi;
 fi;
+
+# Ensure libexec and bin are in $PATH
+for dir in libexec bin; do
+  case ":${PATH}:" in
+    *:${TFENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${TFENV_ROOT}/${dir}', not adding it again";;
+    *) 
+      log 'debug' "\$PATH does not contain '${TFENV_ROOT}/${dir}', prepending and exporting it now";
+      export PATH="${TFENV_ROOT}/${dir}:${PATH}";
+      ;;
+  esac;
+done;
+
+#####################
+# Begin Script Body #
+#####################
 
 [ "${#}" -gt 1 ] && log 'error' 'usage: tfenv install [<version>]';
 
@@ -37,12 +66,25 @@ declare arg="${1:-""}";
 
 if [ -z "${arg}" ]; then
   version_file="$(tfenv-version-file)";
+  log 'debug' "Version File: ${version_file}";
   if [ "${version_file}" != "${TFENV_ROOT}/version" ]; then
-    version_requested="$(cat "${version_file}" || true)";
+    log 'debug' "Version File (${version_file}) is not the default \${TFENV_ROOT}/version (${TFENV_ROOT}/version)";
+    version_requested="$(cat "${version_file}")" \
+      || log 'error' "Failed to open ${version_file}";
+  elif [ -f "${version_file}" ]; then
+    log 'debug' "Version File is the default \${TFENV_ROOT}/version (${TFENV_ROOT}/version)";
+    version_requested="$(cat "${version_file}")" \
+      || log 'error' "Failed to open ${version_file}";
+  else
+    log 'debug' "Version File is the default \${TFENV_ROOT}/version (${TFENV_ROOT}/version) but it doesn't exist";
+    log 'info' 'No version requested on the command line or in the version file search path. Installing "latest"';
+    version_requested='latest';
   fi;
 else
   version_requested="${arg}";
 fi;
+
+log 'debug' "Version Requested: ${version_requested}";
 
 if [[ "${version_requested}" =~ ^min-required$ ]]; then
   log 'info' 'Detecting minimal required version...';
@@ -67,7 +109,10 @@ else
   regex="^${version_requested}$";
 fi;
 
-[ -n "${version}" ] || log 'error' 'Version is not specified';
+[ -n "${version}" ] || log 'error' 'Version is not specified. This should not be possible as we default to latest';
+
+log 'debug' "Processing install for version ${version}, using regex ${regex}";
+
 version="$(tfenv-list-remote | grep -e "${regex}" | head -n 1)";
 [ -n "${version}" ] || log 'error' "No versions matching '${arg}' found in remote";
 
