Add graceful fail for min-required

diff --git a/libexec/tfenv-exec b/libexec/tfenv-exec
--- a/libexec/tfenv-exec
+++ b/libexec/tfenv-exec
@@ -74,10 +74,17 @@ done;
 
 if [[ "${TFENV_TERRAFORM_VERSION-}" =~ ^min-required$ ]]; then
   log 'info' 'TFENV_TERRAFORM_VERSION set to "min-required". Detecting minimum required version...';
-  min_required="$(tfenv-min-required)" || log 'error' 'tfenv-min-required failed';
-  log 'info' "Minimum required version detected: ${min_required}";
-  TFENV_VERSION=${min_required}
-else
+  min_required="$(tfenv-min-required)"
+  if [ $? -ne 0 ]; then
+    log 'info' 'tfenv-min-required failed, falling-back to tfenv-version-name';
+    TFENV_TERRAFORM_VERSION="";
+  else
+    log 'info' "Minimum required version detected: ${min_required}";
+    TFENV_VERSION=${min_required};
+  fi;
+fi;
+
+if [ -z "${TFENV_VERSION+x}" ]; then
   log 'debug' 'Getting version from tfenv-version-name';
   TFENV_VERSION="$(tfenv-version-name)" \
     && log 'debug' "TFENV_VERSION is ${TFENV_VERSION}" \
