Update changelog for rc2

diff --git a/libexec/tfenv-install b/libexec/tfenv-install
--- a/libexec/tfenv-install
+++ b/libexec/tfenv-install
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 function error_and_die() {
-  echo -e "tfenv: $(basename ${0}): [\033[0;31mERROR] ${1}\033[0;39m" >&2
+  echo -e "tfenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
   exit 1
 }
 
@@ -61,8 +61,8 @@ case "$(uname -s)" in
     ;;
 esac
 
-keybase_bin=$(which keybase)
-shasum_bin=$(which shasum)
+keybase_bin="$(which keybase 2>/dev/null)"
+shasum_bin="$(which shasum 2>/dev/null)"
 
 version_url="https://releases.hashicorp.com/terraform/${version}"
 tarball_name="terraform_${version}_${os}.zip"
@@ -73,22 +73,22 @@ info "Installing Terraform v${version}"
 # Create a local temporary directory for downloads
 download_tmp="$(mktemp -d tfenv_download.XXXXXX)" || error_and_die "Unable to create temporary download directory in $(pwd)"
 # Clean it up in case of error
-trap 'rm -rf "${download_tmp}"' EXIT;
+trap "rm -rf ${download_tmp}" EXIT;
 
 info "Downloading release tarball from ${version_url}/${tarball_name}"
-curl -s --tlsv1.2 -f -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
+curl -# --tlsv1.2 -f -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || error_and_die "Tarball download failed"
 info "Downloading SHA hash file from ${version_url}/${shasums_name}"
 curl -s --tlsv1.2 -f -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || error_and_die "SHA256 hashes download failed"
 
 # Verify signature if keybase is present.
 if [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
-  "${keybase_bin}" status | egrep -q '^Logged in:[[:space:]]*yes'
+  "${keybase_bin}" status | grep -Eq '^Logged in:[[:space:]]*yes'
   keybase_logged_in=$?
-  "${keybase_bin}" list-following | fgrep -q hashicorp
+  "${keybase_bin}" list-following | grep -Fq hashicorp
   keybase_following_hc=$?
 
   if [[ "${keybase_logged_in}" -ne 0 || "${keybase_following_hc}" -ne 0 ]]; then
-    warn_and_continue "To verify the GPG signature on the hash file,\nmake sure you're logged into keybase and following hashicorp"
+    warn_and_continue "Unable to verify GPG signature unless logged into keybase and following hashicorp"
   else
     info "Downloading SHA hash signature file from ${version_url}/${shasums_name}.sig"
     curl -s --tlsv1.2 -f -o "${download_tmp}/${shasums_name}.sig" "${version_url}/${shasums_name}.sig" || error_and_die "SHA256SUMS signature download failed"
@@ -102,7 +102,7 @@ fi
 if [[ -n "${shasum_bin}" && -x "${shasum_bin}" ]]; then
   (
     cd "${download_tmp}"
-    "${shasum_bin}" -a 256 -s -c <(fgrep "${tarball_name}" "${shasums_name}") || error_and_die "SHA256 hash does not match!"
+    "${shasum_bin}" -a 256 -s -c <(grep -F "${tarball_name}" "${shasums_name}") || error_and_die "SHA256 hash does not match!"
   )
 else
   # Lack of shasum deserves a proper warning
