adjust the messages to shorten the libexec path

diff --git a/libexec/tfenv-install b/libexec/tfenv-install
--- a/libexec/tfenv-install
+++ b/libexec/tfenv-install
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
 function error_and_die() {
-  echo -e "tfenv: ${0}: [\033[0;31mERROR] ${1}\033[0;39m" >&2
+  echo -e "tfenv: $(basename ${0}): [\033[0;31mERROR] ${1}\033[0;39m" >&2
   exit 1
 }
 
 function warn_and_continue() {
-  echo -e "tfenv: ${0}: \033[0;33m[WARN] ${1}\033[0;39m" >&2
+  echo -e "tfenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
 }
 
 function info() {
